// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpyc8PqHukHWAswEfx50P6trL7GtgocOA',
    appId: '1:117549966594:web:49f4b23d1934cf35258e1b',
    messagingSenderId: '117549966594',
    projectId: 'fideliscan-app-e8488',
    authDomain: 'fideliscan-app-e8488.firebaseapp.com',
    databaseURL: 'https://fideliscan-app-e8488-default-rtdb.firebaseio.com',
    storageBucket: 'fideliscan-app-e8488.firebasestorage.app',
    measurementId: 'G-JBZ0QLZS16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebXVW05RzNwC1-47MVNn2DIQn-rFzm7Q',
    appId: '1:117549966594:android:baa21e2cb8f2ccc8258e1b',
    messagingSenderId: '117549966594',
    projectId: 'fideliscan-app-e8488',
    databaseURL: 'https://fideliscan-app-e8488-default-rtdb.firebaseio.com',
    storageBucket: 'fideliscan-app-e8488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXY_nJN-qEndUJ8DGLgf6JZfXnUFuhhrY',
    appId: '1:117549966594:ios:0c18eb3c1e11758e258e1b',
    messagingSenderId: '117549966594',
    projectId: 'fideliscan-app-e8488',
    databaseURL: 'https://fideliscan-app-e8488-default-rtdb.firebaseio.com',
    storageBucket: 'fideliscan-app-e8488.firebasestorage.app',
    iosClientId: '117549966594-r76b2emcd94ukfi2pnuqlbnq53h48tlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXY_nJN-qEndUJ8DGLgf6JZfXnUFuhhrY',
    appId: '1:117549966594:ios:0c18eb3c1e11758e258e1b',
    messagingSenderId: '117549966594',
    projectId: 'fideliscan-app-e8488',
    databaseURL: 'https://fideliscan-app-e8488-default-rtdb.firebaseio.com',
    storageBucket: 'fideliscan-app-e8488.firebasestorage.app',
    iosClientId: '117549966594-r76b2emcd94ukfi2pnuqlbnq53h48tlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpyc8PqHukHWAswEfx50P6trL7GtgocOA',
    appId: '1:117549966594:web:a479b07714736b36258e1b',
    messagingSenderId: '117549966594',
    projectId: 'fideliscan-app-e8488',
    authDomain: 'fideliscan-app-e8488.firebaseapp.com',
    databaseURL: 'https://fideliscan-app-e8488-default-rtdb.firebaseio.com',
    storageBucket: 'fideliscan-app-e8488.firebasestorage.app',
    measurementId: 'G-FFT0V1RWNF',
  );

}